### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by SteveBarnett** [Onwa2014/internet.org_project#7]
Should contain "what is this?" and set up instructions.

**Comment by Onwa2014** [comment]
Done

**Comment by Onwa2014** [comment]
Here is the commit link https://github.com/Onwa2014/internet.org_project/commit/2fe47d2a9f6d45d71b07a66e7b8fc14a50d225cc

**Comment by Onwa2014** [comment]
https://github.com/Onwa2014/internet.org_project/commit/9c624fbf0063a7a91e3bb18b720871ee48ed8ee1
correct version

**Comment by SteveBarnett** [comment]
@Onwa2014 just one comment: how about `nodemon`? You need to install it with `npm install -g nodemon` before you can use it.

So, how about saying "run it with `node index.js`, or with nodemon (add link to nodemon, maybe with install instructions).

**Comment by Onwa2014** [comment]
Thank you Steve I forgot about that. I have changed it to node index.js

**Comment by SteveBarnett** [comment]
:+1:
